const SESSION_TTL_MS = 1000 * 60 * 60 * 24 * 30;
const SESSION_RENEWAL_THRESHOLD_MS = SESSION_TTL_MS / 2;
const TOKEN_BYTES = 32;
const USER_AGENT_MAX_LENGTH = 255;

export {
  SESSION_TTL_MS,
  SESSION_RENEWAL_THRESHOLD_MS,
  TOKEN_BYTES,
  USER_AGENT_MAX_LENGTH,
};
