const BATCH_SIZE = 200;
const CONCURRENCY = 4;
const DELAY_BETWEEN_SLICES_MS = 300;
const CONSECUTIVE_FAILURE_LIMIT = 30;

export {
  BATCH_SIZE,
  CONCURRENCY,
  DELAY_BETWEEN_SLICES_MS,
  CONSECUTIVE_FAILURE_LIMIT,
};
