const TAXON_FR: Record<string, string> = {
  Animalia: "Animaux",
  Plantae: "Plantes",
  Fungi: "Champignons",
  Chromista: "Chromistes",
  Chordata: "Chordés",
  Arthropoda: "Arthropodes",
  Mollusca: "Mollusques",
  Cnidaria: "Cnidaires",
  Annelida: "Annélides",
  Echinodermata: "Échinodermes",
  Tracheophyta: "Plantes vasculaires",
  Bryophyta: "Mousses",
  Mammalia: "Mammifères",
  Aves: "Oiseaux",
  Reptilia: "Reptiles",
  Amphibia: "Amphibiens",
  Actinopterygii: "Poissons à nageoires rayonnées",
  Chondrichthyes: "Poissons cartilagineux",
  Insecta: "Insectes",
  Arachnida: "Arachnides",
  Malacostraca: "Crustacés",
  Gastropoda: "Gastéropodes",
  Bivalvia: "Bivalves",
  Cephalopoda: "Céphalopodes",
  Anthozoa: "Coraux et anémones",
  Magnoliopsida: "Dicotylédones",
  Liliopsida: "Monocotylédones",
  Pinopsida: "Conifères",
  Polypodiopsida: "Fougères",
  Primates: "Primates",
  Carnivora: "Carnivores",
  Rodentia: "Rongeurs",
  Chiroptera: "Chauves-souris",
  Cetartiodactyla: "Cétartiodactyles",
  Perissodactyla: "Périssodactyles",
  Proboscidea: "Éléphants",
  Testudines: "Tortues",
  Squamata: "Lézards et serpents",
  Crocodylia: "Crocodiles",
  Anura: "Grenouilles et crapauds",
  Caudata: "Salamandres et tritons",
  Passeriformes: "Passereaux",
  Psittaciformes: "Perroquets",
  Accipitriformes: "Rapaces diurnes",
  Lepidoptera: "Papillons",
  Coleoptera: "Coléoptères",
  Odonata: "Libellules",
  Hymenoptera: "Abeilles, guêpes et fourmis",
};

const RANKS = [
  ["kingdom", "Règne"],
  ["phylum", "Embranchement"],
  ["className", "Classe"],
  ["order", "Ordre"],
  ["family", "Famille"],
  ["species", "Espèce"],
] as const;

const SECTIONS = [
  ["range", "Répartition"],
  ["population", "Population"],
  ["habitats", "Habitat et écologie"],
  ["threats", "Menaces"],
  ["measures", "Mesures de conservation"],
  ["use_trade", "Utilisation et commerce"],
] as const;

export { RANKS, SECTIONS, TAXON_FR };
